MAP=sk_mapping.dbmap
DEFINITIONS=*.dbdef
OUTPUT=sql_script(dir=./scripts;file=sk_db.sql)
OUTPUT=markdown_docs(dir=./docs;file=README-DB.md)
OUTPUT=json_definitions(proj=LVD.Stakhanovise.NET)
OUTPUT=create_db(connection_string=;if_exists=drop)
OUTPUT=mapping_code(proj=LVD.Stakhanovise.NET.Common;ns=LVD.Stakhanovise.NET.Model;dir=Model;cls=QueuedTaskMapping)