<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.2.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LVD.Stakhanovise.NET.Logging.Log4NetLogging\LVD.Stakhanovise.NET.Logging.Log4NetLogging.csproj" />
		<ProjectReference Include="..\LVD.Stakhanovise.NET.Logging.Tests.Harness\LVD.Stakhanovise.NET.Logging.Tests.Harness.csproj" />
		<ProjectReference Include="..\LVD.Stakhanovise.NET\LVD.Stakhanovise.NET.csproj" />
	</ItemGroup>

</Project>
